config/routes.rb
Rails.application.routes.draw do
  
  post 'posts/:id/comments/create' => 'comments#create'
  delete 'comments/:id' => 'comments#destroy'
  
  get 'comments/destroy'

  resources :posts
  root 'cafes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #authenticate
  get '/sign_up' => 'authenticate#sign_up'
  post '/sign_up' => 'authenticate#user_sign_up'
  get '/sign_in' => 'authenticate#sign_in'
  post '/sign_in' => 'authenticate#user_sign_in'
  delete '/sign_out' => 'authenticate#sign_out'
  get '/user_info/:user_name' => 'authenticate#user_info'
  
  # cafe
  resources :cafes, except: [:destroy]
  post '/join_cafe/:cafe_id' => 'cafes#join_cafe', as: 'join_cafe'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/daum.rb
class Daum < ApplicationRecord
    has_many :memberships
    has_many :users, through: :memberships
    has_many :posts
    
    #   클래스 메소드 : Daum.find(5)
    # 인스턴스 메소드 : daum = Daum.find(5)
    
    # def self.메소드명 --> 클래스 메소드
    #     로직안에서 self를 쓸 수 없다.
    # end
    
    # def 메소드명 --> 인스턴스 메소드
    #     로직안에서 self를 쓸 수 있음
    #     이 self == 현재 자신 객체
    # end    
    
    def is_member?(user)
        # daum대신 self ==> 현재 자신 객체
        self.users.include?(user)
    end
   
end

app/models/membership.rb
class Membership < ApplicationRecord
    belongs_to :user
    belongs_to :daum
   
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image_path, ImageUploader
    #mount_uploader :file_path, FileUploader
    has_many :comments
    belongs_to :user
    belongs_to :daum
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :user_name, uniqueness: true
    # user_name 컬럼에 unique 속성 부여
    
    has_many :memberships
    has_many :daums, through: :memberships
    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :user_signed_in?, :current_user
  
  def user_signed_in?
      session[:sign_in_user].present?
  end
  
  def authenticate_user!
      redirect_to sign_in_path unless user_signed_in?
  end
  
  def current_user
      @current_user = User.find(session[:sign_in_user]) if user_signed_in?
  end
end

app/controllers/authenticate_controller.rb
class AuthenticateController < ApplicationController
    # 회원가입 페이지
    def sign_up
        @user = User.new
    end
    
    # 실제 회원가입 로직
    def user_sign_up
        @user = User.new(user_name: params[:user_name], 
                         password: params[:password],
                         password_confirmation: params[:password_confirmation])
        
        if @user.save # 
            redirect_to root_path, flash: {success: '회원가입 성공'}
        else
            p @user.errors
            redirect_to :back, flash: {danger: '회원가입 실패'}
        end    
    end    
    
    # 로그인 페이지
    def sign_in
    end
    
    # 실제 로그인 로직
    def user_sign_in
        @user = User.find_by(user_name: params[:user_name]) #
        if @user.present? and @user.authenticate(params[:password])
            session[:sign_in_user] = @user.id
            redirect_to root_path, flash: {success: '로그인 성공'}
        else
            redirect_to :back, flash: {danger: '로그인 정보를 확인하세요'}
        end 
    end
    
    # 유저 정보 페이지

    
    # 로그아웃 로직
    def sign_out
        session.delete(:sign_in_user)
        redirect_to :back, flash: {success: '로그아웃 성공'}
    end
    
end

app/controllers/cafes_controller.rb
class CafesController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    # 전체 카페 목록을 보여주는 페이지
    # -> 로그인 하지 않았을 때 : 전체 카페 목록
    # -> 로그인 했을 때: 유저가 가입한 카페 목록
    def index
        @cafes = Daum.all
    end
    
    # 카페 내용물을 보여주는 페이지(이 카페의 게시물)    
    def show
        @cafe = Daum.find(params[:id])   
        #session[:current_cafe] = @cafe.id
    end
    
    # 카페를 개설하는 페이지
    def new
        @cafe = Daum.new
    end    
        
    # 카페를 실제로 개설하는 로직
    def create
        p params
        @cafe = Daum.new(daum_params)
        @cafe.master_name = current_user.user_name
        
        if @cafe.save 
            Membership.create(daum_id: @cafe.id, user_id: current_user.id)
            redirect_to cafe_path(@cafe), flash: {success: '카페개설 성공'}
        else
            p @cafe.errors
            redirect_to :back, flash: {danger: '카페개설 실패'}
        end                   
    end
    
    # 현재 이 카페에 가입된 유저 중에 지금 로그인한 유저가 있니??
     # 중복가입을 막을 수 없음
        # 1. 가입버튼을 안 보이게 한다. (사용자 화면 조작) -> Model 코딩 (메서드)
        # 2. 중복가입체크 후 진행 (서버에서 로직 조작) -> Model Validation
    def join_cafe
        # 사용자가 가입하려는 카페
        cafe = Daum.find(params[:cafe_id])
        
        # 이 카페에 현재 로그인된 사용자가 가입이 됐는지? 
        #if cafe.users.include? current_user
        if cafe.is_member?(current_user)
            # 포함되었으니 가입실패
            redirect_to :back, flash: {danger: '카페가입 실패. 이미 가입된 카페입니다.'}
        else
            # 가입 성공
            Membership.create(daum_id: params[:cafe_id], user_id: current_user.id)
            redirect_to :back, flash: {success: '카페가입 성공'}
        end    
    end
    
    # 카페 정보 수정하는 페이지
    def edit
       
    end
    
    # 카페 정보를 실제로 수정하는 로직
    def update
         @cafe = Daum.find(params[:id])
    end
    
    private
    def daum_params
        params.require(:daum).permit(:title, :description)
        # :params =>{:daum => {:title => "....", :description => "......."}}
    end    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new
    comment.content = params[:content]
    comment.post_id = params[:id]
    comment.save
    
    redirect_to :back
  end

  def destroy
    comment = Comment.find(params[:id]) #댓글의 id를 가져오는 
    comment.destroy
    
    redirect_to :back
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    #@post.daum_id = session[:current_cafe]
      if @post.save # 
     # session.delete(:current_cafe)
        redirect_to @post, flash: {success: 'Post was successfully created.'}
      else
        p @post.errors
        render :new
      end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
      if @post.update(post_params)
        redirect_to @post, flash: {success: 'Post was successfully updated.'}
      else
        render :edit
      end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
      redirect_to posts_url, flash: {success: 'Post was successfully destroyed.'}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :contents,:daum_id, :image_path)
      # {title: params[:post][:title], contents: [:post][:contents], cafe_id: [:post][:cafe_id]} 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authenticate_helper.rb
module AuthenticateHelper
end

app/helpers/cafes_helper.rb
module CafesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authenticate/sign_in.html.erb
<h1>로그인</h1>
<br>
<%= form_tag do %>
    <%= text_field_tag :user_name %><br>
    <%= password_field_tag :password %><br>
    <%= submit_tag 'Sign In' %>
<% end %>

app/views/authenticate/sign_up.html.erb
<br>
<h1>회원가입</h1>
<%= form_tag do %>
    <%= text_field_tag :user_name %><br>
    <%= password_field_tag :password %><br>
    <%= password_field_tag :password_confirmation %><br>
    <%= submit_tag 'Sign Up' %>
<% end %>

app/views/cafes/index.html.erb
<h1>다음 카페에 오신것을 환영합니다.</h1>

<div class="list-group">
    <% @cafes.each do |cafe| %>
      <%= link_to cafe.title, cafe_path(cafe), class: "list-group-item list-group-item-action" %>
    <% end %>
</div>
<div class="text-center">
    <%= link_to "카페개설하기",new_cafe_path(), class: "btn btn-primary" %>
</div>

app/views/cafes/new.html.erb
<h1>카페 개설하기</h1>
<%= form_for(@cafe, url: cafes_path) do |f| %>
    <%= f.text_field :title %><br>
    <%= f.text_area :description %>
    <%= f.submit 'Create Cafe' %>
<% end %>

app/views/cafes/show.html.erb
<!--카페에 등록된 글( 카페 정보 X )-->
<h1><%= @cafe.title %></h1>
<h3><%= @cafe.description %></h3>


<ul class="list-group">
  <% @cafe.posts.each do |post| %>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <%= link_to "#{post.title}", post_path(post) %><!-- 경로에 id가 붙는 건 post를 붙여서 -->
    <span class="badge badge-primary badge-pill"><%=post.comments.count%></span>
  </li>
  <% end  %>
</ul>

<!-- 새글 등록 버튼 -->
<% #unless @cafe.is_member?(current_user) %>
  <%= link_to "카페가입하기",join_cafe_path(@cafe), method: 'POST' , class: "btn btn-primary" %>
<% #end%>
<%= link_to '새글쓰기', new_post_path(cafe_id: @cafe.id), class: 'btn btn-info'%>
<!--(cafe_id: @cafe.id)-->

app/views/comments/_form.html.erb
<%= form_tag("/posts/#{post.id}/comments/create") do %>
    
    <%= text_field_tag(:content, nil, class: "form-control", placeholder: "내용을 입력하세요") %>
    <br>
    <%= submit_tag("댓글작성", class: "btn btn-primary")%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DaumCafe</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <% flash.each do |k,v|%>
  
      <div data-spy="scroll" class="alert alert-<%= k%>"><%= v %></div>
    <% end  %>
    <div class="container overflow:auto">
    <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post, html: {class: 'text-left'}) do |f| %>
 <%= f.hidden_field :daum_id, value: params[:cafe_id] %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :contents %>
    <%= f.text_field :contents, class: 'form-control' %>
  </div>
  
  <div class="field">
    <%= f.label :image_path %>
    <%= f.file_field :image_path, class: 'form-control' %>
  </div>
  
  <br>
  <div class="actions text-right">
    <%= f.submit '작성하기', class: 'btn btn-info'  %>
    <%= link_to '뒤로가기', posts_path, class: 'btn btn-warning text-white' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<ul class="list-group">
  <% @posts.each do |post| %>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <%= link_to "#{post.title}", post_path(post) %><!-- 경로에 id가 붙는 건 post를 붙여서 -->
    <span class="badge badge-primary badge-pill"><%=post.comments.count%></span>
  </li>
  <% end  %>
</ul>
<br>
<div class="text-right">
<%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<h1>
  <strong>Title:</strong>
  <%= @post.title %>
</h1>
<hr/>

<p>
  <strong>Contents:</strong>
  <%= @post.contents %>
</p>

<p>
  <strong>ImagePath:</strong>
  <img src="<%= @post.image_path %>" width= "100%"/>
</p>

<p>
  <strong>Thumb Fill:</strong>
  <img src="<%= @post.image_path.thumb_Fill %>"/>
</p>

<p>
  <strong>Thumb Fit:</strong>
  <img src="<%= @post.image_path.thumb_Fit %>"/>
</p>

<%= link_to '수정', edit_post_path(@post), class: 'btn btn-warning text-white' %> &nbsp;

<!--@post가 어디 카페에 종속되어있는지 알려준다.-->
<%= link_to '목록', cafe_path(@post.daum), class: 'btn btn-info' %>&nbsp;
<%= link_to '삭제', post_path(@post), class: 'btn btn-danger', method: 'DELETE', data: {confirm: "삭제하시겠습니까?"}%>

<br><br>
<!--  댓글 입력 -->
<%= render 'comments/form' ,post: @post %><br>

<!--  댓글 리스트 -->

<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Content</th>
      <th scope="col">Button</th>
    </tr>
  </thead>
  <tbody>
  <% @post.comments.each do |comment| %>
    <tr>
      <th scope="row"><%= comment.id %></th>
      <td><%= comment.content %></td>
      <td><%= link_to "삭제", "comments/#{comment.id}", class: 'btn btn-danger', method: "delete" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/shared/_footer.html.erb
<footer class="footer">
      <div class="container">
        <span class="text-muted">Place sticky footer content here.</span>
      </div>
    </footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-xl navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Expand at xl</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample06" aria-controls="navbarsExample06" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample06">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <% unless user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign In', sign_in_path, class: 'nav-link' %>
          </li>
          <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown06" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.user_name%></a>
            <div class="dropdown-menu" aria-labelledby="dropdown06">
              <%= link_to 'Sign Out', sign_out_path, method: 'delete', class: 'dropdown-item', data: {confirm:'로그아웃 하시겠습니까?'} %>
            </div>
          </li>
          <% end %>
        </ul>
        <form class="form-inline my-2 my-md-0">
          <input class="form-control" type="text" placeholder="Search">
        </form>
      </div>
    </nav>